# Site settings
title: Jonas Scherer - Web Developer
email: jonaslsl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I really enjoy searching for new solutions, standards and technologies that can improve productivity and change the way that we deal with our daily tasks and projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/jonaslsl/" # the base hostname & protocol for your site
twitter_username: jonasscherer
github_username:  jonaslsl

# Build settings
markdown: kramdown
